  /parameters/query:
    get:
      operationId: 'parameters_query'
      description: 'test of query parameter'
      parameters:
        - in: query
          required: true
          name: qint
          type: integer
      responses:
        'default':
          description: 'default response'

  /parameters_required:
    get:
      operationId: 'parameters_required'
      description: 'test of required field of parameter'
      parameters:
        - in: query
          required: true
          name: t
          type: integer
        - in: query
          required: false
          name: f
          type: integer
        - in: query
          name: n
          type: integer
      responses:
        'default':
          description: 'default response'

  /parameters_override:
    get:
      operationId: 'parameters_override'
      description: 'test of paths.<path>.parameters element'
      parameters:
        - in: query
          required: true
          name: child
          type: integer
        - in: query
          required: true
          name: override_to_int_required
          type: integer
      responses:
        'default':
          description: 'default response'
    parameters:
      - in: query
        required: false
        name: override_to_int_required
        type: string
      - in: query
        required: false
        name: parent
        type: string
